# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

QT += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += c++17

DEFINES += QT_DEPRECATED_WARNINGS

HEADERS += \
    player/player.h \
    player/playerGStreamer.h \
    sliderPlayer.h \
    timer/timer.h \
    videoPlayer/videoPlayer.h \
    videoPlayerApp.h \
    player/playerException.h

SOURCES += \
    main.cpp \
    player/player.cpp \
    player/playerGStreamer.cpp \
    sliderPlayer.cpp \
    timer/timer.cpp \
    videoPlayer/videoPlayer.cpp \
    videoPlayerApp.cpp \
    player/playerException.cpp

FORMS += ./videoPlayerApp.ui

RESOURCES += \
    videoPlayerApp.qrc

CONFIG += console

#MOC_DIR += GeneratedFiles/$(ConfigurationName)

INCLUDEPATH += $(GSTREAMER_1_0_ROOT_MSVC_X86_64)/include/orc-0.4/
INCLUDEPATH += $(GSTREAMER_1_0_ROOT_MSVC_X86_64)/include/
INCLUDEPATH += $(GSTREAMER_1_0_ROOT_MSVC_X86_64)/include/gstreamer-1.0/
INCLUDEPATH += $(GSTREAMER_1_0_ROOT_MSVC_X86_64)/include/glib-2.0/
INCLUDEPATH += $(GSTREAMER_1_0_ROOT_MSVC_X86_64)/lib/glib-2.0/include/

LIBS += "$(GSTREAMER_1_0_ROOT_MSVC_X86_64)/lib/gstreamer-1.0.lib"\
"$(GSTREAMER_1_0_ROOT_MSVC_X86_64)/lib/gstvideo-1.0.lib"\
"$(GSTREAMER_1_0_ROOT_MSVC_X86_64)/lib/gstbase-1.0.lib"\
"$(GSTREAMER_1_0_ROOT_MSVC_X86_64)/lib/gobject-2.0.lib"\
"$(GSTREAMER_1_0_ROOT_MSVC_X86_64)/lib/glib-2.0.lib"\
"$(GSTREAMER_1_0_ROOT_MSVC_X86_64)/lib/intl.lib"\
"$(GSTREAMER_1_0_ROOT_MSVC_X86_64)/lib/gthread-2.0.lib"


# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target
